# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:  

   
   PMD-start:
     name: PMD check
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v1
       - name: maven pmd
         run: mvn pmd:pmd
       - name: maven check
         run: mvn pmd:check

   Verifier:
       name: Verify file
       runs-on: ubuntu-latest
       steps:
         - uses: actions/checkout@v1
         - name: verify file 
           run: mvn verifier:verify
           
spotBugs:

         runs-on: ubuntu-latest
         steps:
           - uses: actions/checkout@v2
           - uses: actions/setup-java@v1
             with:
               java-version: 1.8
           - name: obiettivo
             run: mvn spotbugs:spotbugs
           - name: reportspot.xml
             uses: actions/upload-artifact@v2
             with:
               name: generzione file
               path: target/reportspot.xml
           

  build:
     runs-on: ubuntu-latest

     steps:
     - uses: actions/checkout@v2
     - name: Set up JDK 1.8
       uses: actions/setup-java@v1
       with:
        java-version: 1.8
     - name: Build with Maven
       run: mvn -B package --file pom.xml
     - name: artifact
       uses: actions/upload-artifact@v2
       with:
         path: target/Homework_Aereoporto-1.0-SNAPSHOT.jar
         name: Homework_Aereoporto 

